# Generated by Django 5.1.1 on 2024-09-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_user_role_id_f5c4a2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.vendor'),
        ),
    ]
