# Generated by Django 5.1.1 on 2024-10-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_bookings', to='app.contact'),
        ),
    ]
