# Generated by Django 5.1.1 on 2024-10-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
